services:
  db:
    image: postgres:latest
    container_name: inibsa_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    # Aquí no se ponen rutas, solo el nombre. 
    # Docker gestionará el almacenamiento automáticamente.